source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

rails_version = ENV.fetch("RAILS_VERSION", "~> 7.0")
# Bundle edge Rails instead: gem "rails", github: "rails/rails"
gem "rails", rails_version
# Use sqlite3 as the database for Active Record
if rails_version.include?("~> 7.0")
  gem "sqlite3", "~> 1.4.4"
else
  gem "sqlite3", "~> 2.8.1"
end

# Use Puma as the app server
gem "puma", ">= 4.0"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem "jbuilder", "~> 2.5"
# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 3.0"
# Use ActiveModel has_secure_password
gem "bcrypt", "~> 3.1.7"
gem "observer", "~> 0.1.2"

gem "jwt"
gem "redis"

# Use Capistrano for deployment
# gem "capistrano-rails", group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

eval_gemfile "../dummy_sinatra_api/Gemfile"

group :development, :test do
  gem "rspec-rails", ">= 4.0"
  gem "factory_bot_rails", "~> 4.8"
  gem "capybara"
  gem "rb-readline"
  gem "minitest"
  gem "rack-test"
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

group :test do
  gem "rbnacl"
end
